# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bedb12c6009862534ff3bd3ec36aa029520c9434c88b17fe4250ef4129b23f55109b5aa84c84f7f7a288e48e1f966e13c7c90317f140b837bacaa02ff6158cdc

test:
  secret_key_base: 1c4a30fcf67deb2233bec8e84ad341994762114bec390058e4e63a60007348f6b9194ce14ff0b329a2185c3721215a4792a179a037a01f349746210cd4bc1fe0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
